name:                hochon
version:             0.1.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2024 barsanges

extra-source-files:
- README.md
- LICENSE

synopsis:            A tool to merge and sort bank statements
description:         Please see the README

dependencies:
- base

library:
  source-dirs: src